name: Tests

on: 
  push:
    branches:
      - main
      - master
      - develop
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '**/*.gitignore'
      - '**/*.eslintrc.json'
      - '**/*.dockerignore'
      # - '.github/**'
      
  workflow_dispatch:

env:
  BUILD_BRANCH: ${{ github.ref_name }}
  GIT_TERMINAL_PROMPT: 1

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@main
        with:
          swift-version: "5"
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test